wheels_power_enabled: 240
motion_enabled: 241

hw_ok: 243
wdog_ok: 245
laser_ok: 246
edm_ok: 248
selector_ok: 249
hw_ok_estop: 250
vel_ok: 255

op_mode_auto: 264
op_mode_manual: 265
op_mode_maintenance: 266
# op_mode_emergency: 267

switch_laser_mute_on: 268
switch_laser_mute_off: 269

lsr1_safezone_free: 280
lsr2_safezone_free: 281
lsr1_warningzone1_free: 282
lsr2_warningzone1_free: 283
lsr1_warningzone2_free: 284
lsr2_warningzone2_free: 285

lsr_mode_standard_input: 272
lsr_mode_docking_input: 273
lsr_mode_standby_input: 274
lsr_mode_cart_input: 275
lsr_mode_error: 279

platform_moving: 296
mode_changed: 298
reset_required: 299

# OUTPUT

emergency_stop_sw: 0

buzzer_on_pulse: 3
buzzer_on_intermittent: 4

buzzer_mode_2: 17
buzzer_mode_3: 18

lsr_mode_standard_output: 26
lsr_mode_docking_output: 27
lsr_mode_standby_output: 28
lsr_mode_cart_output: 29