local_costmap:
  global_frame: $(arg odom_frame)
  robot_base_frame: $(arg base_frame)
  update_frequency: 5.0
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_laser_layer_1_2
      type: "costmap_2d::ObstacleLayer"
#    - name: obstacle_laser_layer_3
#      type: "costmap_2d::ObstacleLayer"
#    - name: 3d_lidar_obstacle_layer
#      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
