footprint: [[0.375, -0.34], [0.375, 0.34], [-0.375,0.34], [-0.375, -0.34]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: total_laser
  total_laser:
    data_type: LaserScan
    topic: $(arg total_scan_topic)
    marking: true
    clearing: true 

