# Commands for a robot that is equipped with an elevator
command_list:
  - RLC_PICK
  - RLC_PLACE
  - ELEVATOR

# SERVICES

ELEVATOR:
  type: elevator_service_interface/ElevatorServiceInterface
  namespace: robotnik_base_control/set_elevator

# PROCEDURES

RLC_PICK:
  type: pick_procedure_interface/PickProcedureInterface
  namespace: PickComponent

RLC_PLACE:
  type: place_procedure_interface/PlaceProcedureInterface
  namespace: PlaceComponent
